name: Production code push

on:
  push:
    branches:
      - production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # ---------- Checkout Code ----------
      - name: Checkout repository
        uses: actions/checkout@v4

      # ---------- Setup Node ----------
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      # ---------- Install Dependencies ----------
      - name: Install dependencies
        run: npm install

      # ---------- Run Tests ----------
      #- name: Run tests
       # run: npm test

      # ---------- Build Project ----------
      - name: Build NestJS Project
        run: npm run build

      # ---------- Run DB Migrations (Optional) ----------
      # Enable only if you want migrations to run automatically

